/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CenovnikRouteImport } from './routes/cenovnik'
import { Route as GalerijaRouteImport } from './routes/galerija'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as ZaNasRouteImport } from './routes/za-nas'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CenovnikRoute = CenovnikRouteImport.update({
  id: '/cenovnik',
  path: '/cenovnik',
  getParentRoute: () => rootRouteImport,
} as any)
const GalerijaRoute = GalerijaRouteImport.update({
  id: '/galerija',
  path: '/galerija',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const ZaNasRoute = ZaNasRouteImport.update({
  id: '/za-nas',
  path: '/za-nas',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cenovnik': typeof CenovnikRoute
  '/galerija': typeof GalerijaRoute
  '/kontakt': typeof KontaktRoute
  '/za-nas': typeof ZaNasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cenovnik': typeof CenovnikRoute
  '/galerija': typeof GalerijaRoute
  '/kontakt': typeof KontaktRoute
  '/za-nas': typeof ZaNasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cenovnik': typeof CenovnikRoute
  '/galerija': typeof GalerijaRoute
  '/kontakt': typeof KontaktRoute
  '/za-nas': typeof ZaNasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/cenovnik' | '/galerija' | '/kontakt' | '/za-nas'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cenovnik' | '/galerija' | '/kontakt' | '/za-nas'
  id: '__root__' | '/' | '/cenovnik' | '/galerija' | '/kontakt' | '/za-nas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CenovnikRoute: typeof CenovnikRoute
  GalerijaRoute: typeof GalerijaRoute
  KontaktRoute: typeof KontaktRoute
  ZaNasRoute: typeof ZaNasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cenovnik': {
      id: '/cenovnik'
      path: '/cenovnik'
      fullPath: '/cenovnik'
      preLoaderRoute: typeof CenovnikRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galerija': {
      id: '/galerija'
      path: '/galerija'
      fullPath: '/galerija'
      preLoaderRoute: typeof GalerijaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/za-nas': {
      id: '/za-nas'
      path: '/za-nas'
      fullPath: '/za-nas'
      preLoaderRoute: typeof ZaNasRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CenovnikRoute: CenovnikRoute,
  GalerijaRoute: GalerijaRoute,
  KontaktRoute: KontaktRoute,
  ZaNasRoute: ZaNasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
